# -*- coding: utf-8 -*-

"""
/***************************************************************************
 AutoPipInstaller
                                 A QGIS plugin
 When updating, metadata plugin dependencies will be installed
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-07-16
        copyright            : (C) 2024 by fdobad
        email                : fbadilla@ing.uchile.cl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = "fdobad"
__date__ = "2024-07-16"
__copyright__ = "(C) 2024 by fdobad"

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = "$Format:%H$"

import inspect
import os
import sys

from qgis.core import QgsApplication

from .auto_pip_provider import AutoPipInstallerProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class AutoPipInstallerPlugin(object):

    def __init__(self):
        self.provider = None
        from .once_pip import once_pip

        once_pip()

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = AutoPipInstallerProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
